//! Search dispatch supervisor: owns the fixed-concurrency semaphore,
//! in-flight task registry, last-search cache, and resource monitor
//! that reclaims in-flight tasks when process RSS exceeds the
//! configured soft limit.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Instant;
use tokio::sync::{RwLock, Semaphore};

/// Tunable knobs surfaced via `update_search_settings` IPC.
#[derive(Debug, Clone)]
pub struct SearchSettings {
    pub max_concurrency: usize,
    pub memory_soft_limit_mb: usize,
    pub per_source_timeout_ms: u64,
    pub reclaim_batch: usize,
}

impl Default for SearchSettings {
    fn default() -> Self {
        Self {
            max_concurrency: 8,
            memory_soft_limit_mb: 400,
            per_source_timeout_ms: 2000,
            reclaim_batch: 2,
        }
    }
}

impl SearchSettings {
    /// Clamp values into safe ranges. Returns Err if any value is out
    /// of range (callers should surface the message to the UI).
    pub fn validate(&self) -> Result<(), String> {
        if !(1..=64).contains(&self.max_concurrency) {
            return Err(format!(
                "max_concurrency must be in 1..=64, got {}",
                self.max_concurrency
            ));
        }
        if !(50..=4096).contains(&self.memory_soft_limit_mb) {
            return Err(format!(
                "memory_soft_limit_mb must be in 50..=4096, got {}",
                self.memory_soft_limit_mb
            ));
        }
        if !(500..=60000).contains(&self.per_source_timeout_ms) {
            return Err(format!(
                "per_source_timeout_ms must be in 500..=60000, got {}",
                self.per_source_timeout_ms
            ));
        }
        if !(1..=16).contains(&self.reclaim_batch) {
            return Err(format!(
                "reclaim_batch must be in 1..=16, got {}",
                self.reclaim_batch
            ));
        }
        Ok(())
    }
}

/// One currently-running book source task.
#[derive(Debug, Clone)]
pub struct InFlightTask {
    pub source_url: String,
    pub source_name: String,
    pub health_score: f64,
    pub started_at: Instant,
    pub cancel: tokio::sync::watch::Sender<bool>,
}

/// Frozen snapshot of the last completed (or cancelled) search.
///
/// Note: source statuses and failures are intentionally omitted.
/// These are derived on the frontend from the `SearchEvent` stream
/// (which is re-emitted on re-mount). Storing them on the Rust side
/// would require a parallel struct to the frontend's `SourceStatus`
/// and `SearchFailure` (in `src/types.ts`), and they can always be
/// regenerated by re-running the search. Only fields that are
/// expensive to reproduce (query, results, counts, duration) are
/// kept here.
#[derive(Debug, Clone)]
pub struct SearchSnapshot {
    pub request_id: String,
    pub query: String,
    pub results: Vec<crate::db::models::SearchBook>,
    pub total_results: usize,
    pub duration_ms: u64,
    pub captured_at: Instant,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RequestId(pub String);

/// Public supervisor handle. Cloned via `Arc`.
pub struct SearchSupervisor {
    pub(crate) sem: Arc<Semaphore>,
    pub(crate) in_flight: Arc<RwLock<HashMap<RequestId, Vec<InFlightTask>>>>,
    pub(crate) last_search: Arc<tokio::sync::Mutex<Option<SearchSnapshot>>>,
    pub(crate) settings: Arc<RwLock<SearchSettings>>,
    pub(crate) current_request: Arc<tokio::sync::Mutex<Option<RequestId>>>,
    /// Tracks the latest resources monitor task so we can abort it on
    /// drop or supervisor replacement. Only one monitor at a time.
    pub(crate) monitor_handle: Arc<tokio::sync::Mutex<Option<tokio::task::JoinHandle<()>>>>,
    /// App handle, kept for future use (e.g. emitting events from the
    /// resource monitor). `None` in tests where constructing a real
    /// AppHandle is impractical.
    pub(crate) app_handle: Option<tauri::AppHandle>,
}

impl SearchSupervisor {
    /// Build a new supervisor with default settings. The caller is
    /// responsible for starting the resource monitor via
    /// `start_resource_monitor`.
    pub fn new(app_handle: tauri::AppHandle) -> Self {
        let defaults = SearchSettings::default();
        let sem = Arc::new(Semaphore::new(defaults.max_concurrency));
        Self {
            sem,
            in_flight: Arc::new(RwLock::new(HashMap::new())),
            last_search: Arc::new(tokio::sync::Mutex::new(None)),
            settings: Arc::new(RwLock::new(defaults)),
            current_request: Arc::new(tokio::sync::Mutex::new(None)),
            monitor_handle: Arc::new(tokio::sync::Mutex::new(None)),
            app_handle: Some(app_handle),
        }
    }

    /// Submit a new search. If a previous search is in flight, all
    /// its in-flight tasks are cancelled (cancel handles fired). The
    /// method does NOT wait for the stream to finish — it returns
    /// the new request id once dispatch begins. The stream runs in
    /// the background and writes `last_search` upon completion.
    pub async fn submit(&self, request_id: String) {
        // Mark the new request as current. Existing in-flight tasks
        // for any prior request will be cancelled below.
        let new_id = RequestId(request_id);
        let old_id = {
            let mut current = self.current_request.lock().await;
            let old = current.take();
            *current = Some(new_id.clone());
            old
        };

        // Fire cancel on any in-flight tasks from the old request.
        if let Some(prev) = old_id {
            let in_flight = self.in_flight.read().await;
            if let Some(tasks) = in_flight.get(&prev) {
                for t in tasks {
                    let _ = t.cancel.send(true);
                }
            }
        }
        // Note: we do NOT clear in_flight[old] here. The src_task
        // removes itself upon completion (see Task 5). If the user
        // submits again before the old tasks finish, the next
        // submit() will see the leftover entries and fire their
        // cancel handles again — sending `true` on an already-closed
        // channel is a no-op, so this is safe.
    }

    /// Cancel all in-flight tasks for the given request id (or the
    /// current request if `None`). Returns the number of tasks
    /// whose cancel handles were fired.
    pub async fn cancel(&self, request_id: Option<String>) -> usize {
        let target = match request_id {
            Some(id) => RequestId(id),
            None => {
                let cur = self.current_request.lock().await;
                match cur.as_ref() {
                    Some(id) => id.clone(),
                    None => return 0,
                }
            }
        };
        let mut fired = 0usize;
        let in_flight = self.in_flight.read().await;
        if let Some(tasks) = in_flight.get(&target) {
            for t in tasks {
                let _ = t.cancel.send(true);
                fired += 1;
            }
        }
        fired
    }

    /// Cancel up to `batch` in-flight tasks, picking the ones that
    /// are oldest (lower `started_at`) AND have the lowest
    /// `health_score`. Tasks with identical keys are cancelled in
    /// unspecified order. Returns the number of tasks cancelled.
    ///
    /// Safe to call concurrently with `submit` / `cancel`: we hold
    /// the read lock while collecting and only release the cancel
    /// `Sender` clone afterwards (we use the existing sender, not
    /// a clone, so this is fine).
    pub async fn reclaim(&self, batch: usize) -> usize {
        if batch == 0 {
            return 0;
        }
        let to_cancel: Vec<tokio::sync::watch::Sender<bool>> = {
            let map = self.in_flight.read().await;
            let mut all: Vec<&InFlightTask> =
                map.values().flat_map(|v| v.iter()).collect();
            // Sort: oldest first (smaller started_at), then lowest
            // health first (smaller health_score).
            all.sort_by(|a, b| {
                a.started_at
                    .cmp(&b.started_at)
                    .then(a.health_score.partial_cmp(&b.health_score).unwrap_or(std::cmp::Ordering::Equal))
            });
            all.into_iter()
                .take(batch)
                .map(|t| t.cancel.clone())
                .collect()
        };
        let mut fired = 0usize;
        for tx in to_cancel {
            if tx.send(true).is_ok() {
                fired += 1;
            }
        }
        fired
    }

    /// Read the last completed search snapshot, if any.
    pub async fn last_search(&self) -> Option<SearchSnapshot> {
        self.last_search.lock().await.clone()
    }

    /// Replace the supervisor's settings. Validates the new settings
    /// first; returns Err on invalid values.
    pub async fn update_settings(&self, new: SearchSettings) -> Result<(), String> {
        new.validate()?;
        *self.settings.write().await = new;
        Ok(())
    }

    /// Read the current settings.
    pub async fn settings(&self) -> SearchSettings {
        self.settings.read().await.clone()
    }

    /// Test-only constructor that doesn't require a real Tauri app
    /// handle. Used by the unit tests in this module.
    #[cfg(test)]
    pub fn new_for_tests() -> Self {
        let defaults = SearchSettings::default();
        let sem = Arc::new(Semaphore::new(defaults.max_concurrency));
        Self {
            sem,
            in_flight: Arc::new(RwLock::new(HashMap::new())),
            last_search: Arc::new(tokio::sync::Mutex::new(None)),
            settings: Arc::new(RwLock::new(defaults)),
            current_request: Arc::new(tokio::sync::Mutex::new(None)),
            monitor_handle: Arc::new(tokio::sync::Mutex::new(None)),
            app_handle: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn settings_default_is_valid() {
        assert!(SearchSettings::default().validate().is_ok());
    }

    #[test]
    fn settings_reject_zero_concurrency() {
        let mut s = SearchSettings::default();
        s.max_concurrency = 0;
        assert!(s.validate().is_err());
    }

    #[test]
    fn settings_reject_high_concurrency() {
        let mut s = SearchSettings::default();
        s.max_concurrency = 65;
        assert!(s.validate().is_err());
    }

    #[test]
    fn settings_reject_low_memory_limit() {
        let mut s = SearchSettings::default();
        s.memory_soft_limit_mb = 49;
        assert!(s.validate().is_err());
    }

    #[test]
    fn settings_reject_high_memory_limit() {
        let mut s = SearchSettings::default();
        s.memory_soft_limit_mb = 5000;
        assert!(s.validate().is_err());
    }

    #[test]
    fn settings_reject_low_timeout() {
        let mut s = SearchSettings::default();
        s.per_source_timeout_ms = 100;
        assert!(s.validate().is_err());
    }

    #[test]
    fn settings_accept_boundary_values() {
        let s = SearchSettings {
            max_concurrency: 1,
            memory_soft_limit_mb: 50,
            per_source_timeout_ms: 500,
            reclaim_batch: 1,
        };
        assert!(s.validate().is_ok());

        let s = SearchSettings {
            max_concurrency: 64,
            memory_soft_limit_mb: 4096,
            per_source_timeout_ms: 60000,
            reclaim_batch: 16,
        };
        assert!(s.validate().is_ok());
    }

    #[tokio::test]
    async fn submit_sets_current_request() {
        let sup = SearchSupervisor::new_for_tests();
        sup.submit("req-1".to_string()).await;
        let cur = sup.current_request.lock().await;
        assert_eq!(cur.as_ref().map(|r| r.0.clone()), Some("req-1".to_string()));
    }

    #[tokio::test]
    async fn second_submit_replaces_current_request() {
        let sup = SearchSupervisor::new_for_tests();
        sup.submit("req-1".to_string()).await;
        sup.submit("req-2".to_string()).await;
        let cur = sup.current_request.lock().await;
        assert_eq!(cur.as_ref().map(|r| r.0.clone()), Some("req-2".to_string()));
    }

    #[tokio::test]
    async fn cancel_returns_zero_when_no_current_request() {
        let sup = SearchSupervisor::new_for_tests();
        let n = sup.cancel(None).await;
        assert_eq!(n, 0);
    }

    #[tokio::test]
    async fn cancel_fires_handle_for_in_flight_task() {
        let sup = SearchSupervisor::new_for_tests();
        sup.submit("req-1".to_string()).await;
        // Manually insert an in-flight task with a watch channel.
        let (tx, mut rx) = tokio::sync::watch::channel(false);
        let task = InFlightTask {
            source_url: "u".to_string(),
            source_name: "n".to_string(),
            health_score: 1.0,
            started_at: Instant::now(),
            cancel: tx,
        };
        {
            let mut map = sup.in_flight.write().await;
            map.entry(RequestId("req-1".to_string()))
                .or_default()
                .push(task);
        }
        let n = sup.cancel(Some("req-1".to_string())).await;
        assert_eq!(n, 1);
        rx.changed().await.unwrap();
        assert!(*rx.borrow());
    }

    #[tokio::test]
    async fn cancel_does_not_touch_other_requests() {
        let sup = SearchSupervisor::new_for_tests();
        let (tx_a, mut rx_a) = tokio::sync::watch::channel(false);
        let (tx_b, _rx_b) = tokio::sync::watch::channel(false);
        {
            let mut map = sup.in_flight.write().await;
            map.entry(RequestId("req-a".to_string()))
                .or_default()
                .push(InFlightTask {
                    source_url: "a".into(),
                    source_name: "na".into(),
                    health_score: 1.0,
                    started_at: Instant::now(),
                    cancel: tx_a,
                });
            map.entry(RequestId("req-b".to_string()))
                .or_default()
                .push(InFlightTask {
                    source_url: "b".into(),
                    source_name: "nb".into(),
                    health_score: 1.0,
                    started_at: Instant::now(),
                    cancel: tx_b,
                });
        }
        let n = sup.cancel(Some("req-a".to_string())).await;
        assert_eq!(n, 1);
        rx_a.changed().await.unwrap();
        assert!(*rx_a.borrow());
        // rx_b untouched
    }

    #[tokio::test]
    async fn update_settings_writes_and_validates() {
        let sup = SearchSupervisor::new_for_tests();
        let mut new = SearchSettings::default();
        new.max_concurrency = 4;
        sup.update_settings(new.clone()).await.unwrap();
        assert_eq!(sup.settings().await.max_concurrency, 4);

        let mut bad = SearchSettings::default();
        bad.max_concurrency = 0;
        assert!(sup.update_settings(bad).await.is_err());
    }

    #[tokio::test]
    async fn last_search_initially_none() {
        let sup = SearchSupervisor::new_for_tests();
        assert!(sup.last_search().await.is_none());
    }

    #[tokio::test]
    async fn reclaim_picks_oldest_first() {
        let sup = SearchSupervisor::new_for_tests();
        let (tx_old, mut rx_old) = tokio::sync::watch::channel(false);
        let (tx_new, _rx_new) = tokio::sync::watch::channel(false);
        {
            let mut map = sup.in_flight.write().await;
            let entry = map
                .entry(RequestId("req-x".to_string()))
                .or_default();
            // Insert "new" first, then "old" with an earlier Instant
            // (Instant is monotonic, so we sleep briefly).
            entry.push(InFlightTask {
                source_url: "new".into(),
                source_name: "n".into(),
                health_score: 1.0,
                started_at: Instant::now(),
                cancel: tx_new,
            });
            tokio::time::sleep(std::time::Duration::from_millis(10)).await;
            entry.push(InFlightTask {
                source_url: "old".into(),
                source_name: "o".into(),
                health_score: 1.0,
                started_at: Instant::now(),
                cancel: tx_old,
            });
        }
        let n = sup.reclaim(1).await;
        assert_eq!(n, 1);
        // Old was fired
        rx_old.changed().await.unwrap();
        assert!(*rx_old.borrow());
    }

    #[tokio::test]
    async fn reclaim_zero_batch_is_noop() {
        let sup = SearchSupervisor::new_for_tests();
        let (tx, _rx) = tokio::sync::watch::channel(false);
        {
            let mut map = sup.in_flight.write().await;
            map.entry(RequestId("req".to_string())).or_default().push(
                InFlightTask {
                    source_url: "u".into(),
                    source_name: "n".into(),
                    health_score: 1.0,
                    started_at: Instant::now(),
                    cancel: tx,
                },
            );
        }
        let n = sup.reclaim(0).await;
        assert_eq!(n, 0);
    }
}
