//! Search dispatch supervisor: owns the fixed-concurrency semaphore,
//! in-flight task registry, last-search cache, and resource monitor
//! that reclaims in-flight tasks when process RSS exceeds the
//! configured soft limit.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Instant;
use tokio::sync::{RwLock, Semaphore};

/// Tunable knobs surfaced via `update_search_settings` IPC.
#[derive(Debug, Clone)]
pub struct SearchSettings {
    pub max_concurrency: usize,
    pub memory_soft_limit_mb: usize,
    pub per_source_timeout_ms: u64,
    pub reclaim_batch: usize,
}

impl Default for SearchSettings {
    fn default() -> Self {
        Self {
            max_concurrency: 8,
            memory_soft_limit_mb: 400,
            per_source_timeout_ms: 2000,
            reclaim_batch: 2,
        }
    }
}

impl SearchSettings {
    /// Clamp values into safe ranges. Returns Err if any value is out
    /// of range (callers should surface the message to the UI).
    pub fn validate(&self) -> Result<(), String> {
        if !(1..=64).contains(&self.max_concurrency) {
            return Err(format!(
                "max_concurrency must be in 1..=64, got {}",
                self.max_concurrency
            ));
        }
        if !(50..=4096).contains(&self.memory_soft_limit_mb) {
            return Err(format!(
                "memory_soft_limit_mb must be in 50..=4096, got {}",
                self.memory_soft_limit_mb
            ));
        }
        if !(500..=60000).contains(&self.per_source_timeout_ms) {
            return Err(format!(
                "per_source_timeout_ms must be in 500..=60000, got {}",
                self.per_source_timeout_ms
            ));
        }
        if !(1..=16).contains(&self.reclaim_batch) {
            return Err(format!(
                "reclaim_batch must be in 1..=16, got {}",
                self.reclaim_batch
            ));
        }
        Ok(())
    }
}

/// One currently-running book source task.
#[derive(Debug, Clone)]
pub struct InFlightTask {
    pub source_url: String,
    pub source_name: String,
    pub health_score: f64,
    pub started_at: Instant,
    pub cancel: tokio::sync::watch::Sender<bool>,
}

/// Frozen snapshot of the last completed (or cancelled) search.
///
/// Note: source statuses and failures are intentionally omitted.
/// These are derived on the frontend from the `SearchEvent` stream
/// (which is re-emitted on re-mount). Storing them on the Rust side
/// would require a parallel struct to the frontend's `SourceStatus`
/// and `SearchFailure` (in `src/types.ts`), and they can always be
/// regenerated by re-running the search. Only fields that are
/// expensive to reproduce (query, results, counts, duration) are
/// kept here.
#[derive(Debug, Clone)]
pub struct SearchSnapshot {
    pub request_id: String,
    pub query: String,
    pub results: Vec<crate::db::models::SearchBook>,
    pub total_results: usize,
    pub duration_ms: u64,
    pub captured_at: Instant,
}

#[derive(Debug, Clone)]
pub struct RequestId(pub String);

/// Public supervisor handle. Cloned via `Arc`.
pub struct SearchSupervisor {
    pub(crate) sem: Arc<Semaphore>,
    pub(crate) in_flight: Arc<RwLock<HashMap<RequestId, Vec<InFlightTask>>>>,
    pub(crate) last_search: Arc<tokio::sync::Mutex<Option<SearchSnapshot>>>,
    pub(crate) settings: Arc<RwLock<SearchSettings>>,
    pub(crate) current_request: Arc<tokio::sync::Mutex<Option<RequestId>>>,
    /// Tracks the latest resources monitor task so we can abort it on
    /// drop or supervisor replacement. Only one monitor at a time.
    pub(crate) monitor_handle: Arc<tokio::sync::Mutex<Option<tokio::task::JoinHandle<()>>>>,
    pub(crate) app_handle: tauri::AppHandle,
}

impl SearchSupervisor {
    /// Build a new supervisor with default settings. The caller is
    /// responsible for starting the resource monitor via
    /// `start_resource_monitor`.
    pub fn new(app_handle: tauri::AppHandle) -> Self {
        let defaults = SearchSettings::default();
        let sem = Arc::new(Semaphore::new(defaults.max_concurrency));
        Self {
            sem,
            in_flight: Arc::new(RwLock::new(HashMap::new())),
            last_search: Arc::new(tokio::sync::Mutex::new(None)),
            settings: Arc::new(RwLock::new(defaults)),
            current_request: Arc::new(tokio::sync::Mutex::new(None)),
            monitor_handle: Arc::new(tokio::sync::Mutex::new(None)),
            app_handle,
        }
    }
}
